services:
  - type: web
    name: github-photo-backup-webviewer
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: NODE_VERSION
        value: 20
